export const appointmentAssociations: Record<string, number> = {
	'appointments:contacts': 906,
	'appointments:companies': 908,
	'appointments:deals': 944,
	'appointments:tickets': 946,
	'appointments:calls': 912,
	'appointments:emails': 916,
	'appointments:meetings': 918,
	'appointments:notes': 920,
	'appointments:tasks': 922,
	'appointments:communications': 924,
	'appointments:postal_mail': 926,
	'appointments:projects': 1325,
	'appointments:marketing_events': 2728,
};
