export const companyAssociations: Record<string, number> = {
	'companies:companies': 450,
	'companies:contacts': 280,
	'companies:deals': 342,
	'companies:tickets': 340,
	'companies:calls': 181,
	'companies:emails': 185,
	'companies:leads': 611,
	'companies:meetings': 187,
	'companies:notes': 189,
	'companies:tasks': 191,
	'companies:communications': 87,
	'companies:postal_mail': 460,
	'companies:invoices': 180,
	'companies:orders': 934,
	'companies:payments': 389,
	'companies:payment_links': 471,
	'companies:quotes': 72,
	'companies:subscriptions': 297,
	'companies:appointments': 908,
	'companies:courses': 938,
	'companies:listings': 884,
	'companies:services': 792,
	'companies:feedback_submissions': 928,
	'companies:projects': 1236,
	'companies:marketing_events': 1374,
};
