export const contactAssociations: Record<string, number> = {
	'contacts:contacts': 449,
	'contacts:companies': 279,
	'contacts:deals': 4,
	'contacts:tickets': 15,
	'contacts:calls': 193,
	'contacts:emails': 197,
	'contacts:meetings': 199,
	'contacts:notes': 201,
	'contacts:tasks': 203,
	'contacts:communications': 81,
	'contacts:postal_mail': 454,
	'contacts:carts': 586,
	'contacts:orders': 507,
	'contacts:invoices': 178,
	'contacts:payments': 387,
	'contacts:payment_links': 469,
	'contacts:subscriptions': 295,
	'contacts:appointments': 906,
	'contacts:courses': 860,
	'contacts:listings': 882,
	'contacts:services': 798,
	'contacts:feedback_submissions': 97,
	'contacts:projects': 1242,
	'contacts:leads': 609,
	'contacts:quotes': 70,
	'contacts:marketing_events': 1386,
};
