export const invoiceAssociations: Record<string, number> = {
	'invoices:contacts': 177,
	'invoices:companies': 179,
	'invoices:deals': 175,
	'invoices:quotes': 407,
	'invoices:subscriptions': 622,
	'invoices:payment_links': 815,
	'invoices:orders': 517,
	'invoices:tickets': 986,
	'invoices:line_items': 409,
	'invoices:discounts': 411,
	'invoices:fees': 413,
	'invoices:taxes': 415,
	'invoices:payments': 541,
	'invoices:payment_schedule_installments': 691,
	'invoices:data_sync_states': 679,
	'invoices:feedback_submissions': 1160,
};
