export const listingAssociations: Record<string, number> = {
	'listings:contacts': 882,
	'listings:companies': 884,
	'listings:deals': 886,
	'listings:tickets': 942,
	'listings:calls': 890,
	'listings:emails': 894,
	'listings:meetings': 896,
	'listings:notes': 898,
	'listings:tasks': 900,
	'listings:communications': 902,
	'listings:postal_mail': 904,
	'listings:projects': 1321,
	'listings:marketing_events': 2772,
};
