export const marketingEventAssociations: Record<string, number> = {
	'marketing_events:contacts': 1374,
	'marketing_events:companies': 1386,
	'marketing_events:deals': 1388,
	'marketing_events:campaigns': 492,
	'marketing_events:communications': 1234,
	'marketing_events:notes': 259,
	'marketing_events:emails': 497,
	'marketing_events:calls': 1228,
	'marketing_events:tasks': 261,
	'marketing_events:engagements': 493,
	'marketing_events:orders': 2537,
	'marketing_events:commerce_payments': 2535,
	'marketing_events:projects': 1251,
	'marketing_events:appointments': 2729,
	'marketing_events:meeting_events': 499,
	'marketing_events:courses': 2761,
	'marketing_events:listings': 2773,
	'marketing_events:services': 2783,
	'marketing_events:leads': 1390,
	'marketing_events:conversation_sessions': 1232,
	'marketing_events:marketing_events': 2563,
	'marketing_events:publishing_tasks': 1231,
	'marketing_events:users': 2592,
};