export const quoteAssociations: Record<string, number> = {
	'quotes:contacts': 69,
	'quotes:billing_contacts': 1226,
	'quotes:companies': 71,
	'quotes:billing_companies': 1334,
	'quotes:deals': 64,
	'quotes:line_items': 67,
	'quotes:quote_templates': 286,
	'quotes:discounts': 361,
	'quotes:fees': 363,
	'quotes:taxes': 365,
	'quotes:tasks': 217,
	'quotes:signer_contacts': 702,
	'quotes:carts': 732,
	'quotes:invoices': 408,
	'quotes:orders': 731,
	'quotes:payments': 398,
	'quotes:subscriptions': 303,
	'quotes:feedback_submissions': 1172,
};
