export const quoteAssociations: Record<string, number> = {
	'quotes:contacts': 69,
	'quotes:billing_contacts': 1226,
	'quotes:companies': 71,
	'quotes:billing_companies': 1334,
	'quotes:deals': 64,
	'quotes:line_items': 67,
	'quotes:quote_templates': 286,
	'quotes:discounts': 362,
	'quotes:fees': 364,
	'quotes:taxes': 366,
	'quotes:tasks': 217,
	'quotes:signer_contacts': 702,
	'quotes:carts': 733,
	'quotes:invoices': 408,
	'quotes:orders': 731,
	'quotes:payments': 398,
	'quotes:subscriptions': 304,
	'quotes:feedback_submissions': 1172,
};
