export const serviceAssociations: Record<string, number> = {
	'services:contacts': 798,
	'services:companies': 792,
	'services:deals': 794,
	'services:tickets': 796,
	'services:calls': 840,
	'services:emails': 842,
	'services:meetings': 838,
	'services:notes': 836,
	'services:tasks': 852,
	'services:communications': 846,
	'services:postal_mail': 848,
	'services:projects': 1245,
	'services:marketing_events': 2782,
};
