export const ticketAssociations: Record<string, number> = {
	'tickets:tickets': 452,
	'tickets:contacts': 16,
	'tickets:companies': 339,
	'tickets:primary_company': 26,
	'tickets:deals': 28,
	'tickets:calls': 219,
	'tickets:emails': 223,
	'tickets:meetings': 225,
	'tickets:notes': 227,
	'tickets:tasks': 229,
	'tickets:communications': 84,
	'tickets:postal_mail': 456,
	'tickets:threads': 32,
	'tickets:conversations': 278,
	'tickets:orders': 526,
	'tickets:appointments': 947,
	'tickets:courses': 941,
	'tickets:listings': 943,
	'tickets:services': 797,
	'tickets:subscriptions': 1122,
	'tickets:payments': 1355,
	'tickets:feedback_submissions': 99,
	'tickets:projects': 1241,
};
